Initial refactoring to support workload projection
halkyonio/primaza-poc pull request #194
Opened 2022-12-02 16:14 UTC by cmoulliard

- Initial refactoring to support workload projection
- #193

2022-12-02 16:22 UTC, aureamunoz requested changes

2022-12-02 16:22 UTC, aureamunoz commented on servicebox-app/src/test/java/io/halkyon/ApplicationsPageTest.java
>                  .mountSecretInApplication(argThat(new ApplicationNameMatcher(appName)),
You need to add the new param `type`to the [KubernetesClientService#mountSecret method](https://github.com/halkyonio/primaza-poc/blob/d69362960eb59f1f31ef7e91e5db229223657a15/servicebox-app/src/main/java/io/halkyon/services/KubernetesClientService.java#L122)

2022-12-02 17:45 UTC, aureamunoz approved these changes

2022-12-02 17:45 UTC, aureamunoz commented
To be merged @cmoulliard

2022-12-02 18:57 UTC, cmoulliard commented on servicebox-app/src/test/java/io/halkyon/ApplicationsPageTest.java
>                  .mountSecretInApplication(argThat(new ApplicationNameMatcher(appName)),
Fixed. Many thanks

2022-12-03 16:05 UTC, merged

2022-12-03 16:38 UTC, cmoulliard commented
You merged it too early as some changes are still needed to populate correctly the Deployment:
- Set the ENV VAR `SERVICE_BINDING_ROOT = `/binding` 
- Mount the volume of the secret within the container and specify the mountPath
```
        volumeMounts:
        - mountPath: /binding/<SECRET_NAME>
          name: <SECRET_NAME>
```
@aureamunoz